runtime: nodejs
env: flex

env_variables:
  POSTGRES_URL: postgresql://production:l27P4gE38ZC2nesHc18nT03z@172.19.208.3:5432/hangoutrooms
  POSTGRES_USER: production
  POSTGRES_PASSWORD: l27P4gE38ZC2nesHc18nT03z
  POSTGRES_DATABASE: hangoutrooms
  INSTANCE_CONNECTION_NAME: hangoutrooms:us-west4:hangoutroomsdb

beta_settings:
  cloud_sql_instances: hangoutrooms:us-west4:hangoutroomsdb=tcp:5432
